<?php defined('_ENGINE') or die('Access Denied'); return array (
  0 => 'Activity',
  1 => 'Album',
  2 => 'Announcement',
  3 => 'Authorization',
  4 => 'Core',
  5 => 'Event',
  6 => 'Fields',
  7 => 'Forum',
  8 => 'Invite',
  9 => 'Messages',
  10 => 'Music',
  11 => 'Network',
  12 => 'Payment',
  13 => 'Storage',
  14 => 'User',
  15 => 'Video',
  16 => 'Ynfullslider',
  17 => 'Ynfundraising',
  18 => 'Ynmobile',
  19 => 'Ynmultilisting',
  20 => 'Ynrestapi',
  21 => 'Yntheme',
  22 => 'Ynultimatevideo',
  23 => 'Ynvideochannel',
  24 => 'YounetCore',
); ?>