<?php
/**
 * SocialEngine
 *
 * @category   Application_Extensions
 * @package    Sitelike
 * @copyright  Copyright 2010-2011 BigStep Technologies Pvt. Ltd.
 * @license    http://www.socialengineaddons.com/license/
 * @version    $Id: chnagelog.php.tpl 2011-05-05 9:40:21Z SocialEngineAddOns $
 * @author     SocialEngineAddOns
 */
return array(
	'4.1.7p3' => array(
		'Plugin/Core.php' => 'Minor optimizations',
		'Api/Core.php' => 'Fixed issue with One way friendship, Log error solved ',
		'settings/manifest.php' => 'Incremented Version',
		'settings/my.sql' => 'Incremented Version',
		'widgets/mix-like/index.tpl' => 'Added',
		'externals/styles/main.css' => 'Removed extra CSS, CSS Optimizations, Add CSS',
		'views/scripts/admin-global/index.tpl' => 'Minor Optimizations, Removed extra CSS and Code, Confirmation message in Global Settings',
		'views/scripts/admin-global/readme.tpl' => 'Minor Optimizations, Removed extra CSS and Code',
		'views/scripts/admin-mix/index.tpl' => 'Minor Optimizations, Removed extra CSS and Code',
		' views/scripts/admin-settings/index.tpl' => 'Minor Optimizations, Removed extra CSS and Code',
		'views/scripts/admin-settings/likesettings.tpl ' => 'Minor Optimizations, Removed extra CSS and Code',
		'views/scripts/admin-widgets/index.tpl ' => 'Minor Optimizations, Removed extra CSS and Code',
		'views/scripts/common_like_widget.tpl ' => 'Minor Optimizations, Removed extra CSS and Code',
		'views/scripts/content_friend_mylike.tpl ' => 'Minor Optimizations, Removed extra CSS and Code',
		'views/scripts/friend_mycontent_likelist.tpl ' => 'Minor Optimizations, Removed extra CSS and Code',
		'views/scripts/index/compose.tpl ' => 'Minor Optimizations, Removed extra CSS and Code',
		'views/scripts/index/likesettings.tpl ' => 'Minor Optimizations, Removed extra CSS and Code',
		'views/scripts/index/memberlike.tpl ' => 'Minor Optimizations, Removed extra CSS and Code',
		'views/scripts/index/myfriendlikes.tpl ' => 'Minor Optimizations, Removed extra CSS and Code',
		'views/scripts/index/profileuserlikes.tpl' => 'Minor Optimizations, Removed extra CSS and Code',
		'widgets/common-friend-like/index.tpl ' => 'Minor Optimizations, Removed extra CSS and Code, Log error solved',
		'widgets/common-like/index.tpl ' => 'Minor Optimizations, Removed extra CSS and Code',
		'widgets/list-browse-mixlikes/index.tpl ' => 'Minor Optimizations, Removed extra CSS and Code',
		'widgets/widgets/member-friend-like/index.tpl ' => 'Minor Optimizations, Removed extra CSS and Code',
		'widgets/widgets/member-like/index.tpl ' => 'Minor Optimizations, Removed extra CSS and Code',
		'widgets/profile-user-likes/index.tpl ' => 'Minor Optimizations, Removed extra CSS and Code',
		'views/scripts/_my-friends-likes.tpl' => 'Modified "Suggest to Friend" link url',
		'widgets/controllers/IndexController.php' => 'Worked on Indentation',
		'widgets/widgets/list-like-pagealbums/Controller.php' => 'Worked on Indentation',
		'views/scripts/suggestion_link_settings.tpl' => 'Deleted extra files',
		'controllers/AdminGlobalController.php' => 'Confirmation message in Global Settings',
		'externals/styles/mobile.css' => 'Added Mobile Compatibility',
  ),
	'4.1.7p1' => array(
		'Api/Core.php' => 'Modified storage method',
		'Api/likesettings.php' => 'Modified storage method',
		'controllers/AdminSettingsController.php' => 'Modified storage method',
		'Form/Admin/Likesettings.php' => 'Modified storage method',
		'externals/styles/likesettings.css' => 'Minor optimizations',
		'externals/styles/likesettingsorignal.css' => 'Minor optimizations',
		'Plugin/Menus.php' => 'Minor optimizations',
		'controllers/AdminGlobalController.php' => 'Minor optimizations',
		'settings/my.sql' => 'Incremented version',
		'settings/my-upgrade-4.1.7-4.1.7p1.sql' => 'Added',
		'settings/manifest.php' => 'Incremented version',
		'widgets/common-friend-like' => 'Added',
		'widgets/common-like' => 'Added',
		'widgets/event-friend-like/Controller.php' => 'Minor optimizations',
		'widgets/event-friend-like/index.tpl' => 'Minor optimizations',
		'widgets/event-like-button/Controller.php' => 'Minor optimizations',
		'widgets/event-like/Controller.php' => 'Minor optimizations',
		'widgets/event-like/index.tpl' => 'Minor optimizations',
		'widgets/group-friend-like/Controller.php' => 'Minor optimizations',
		'widgets/group-friend-like/index.tpl' => 'Minor optimizations',
		'widgets/group-like-button/Controller.php' => 'Minor optimizations',
		'widgets/group-like/Controller.php' => 'Minor optimizations',
		'widgets/group-like/index.tpl' => 'Minor optimizations',
		'widgets/list-friend-like/Controller.php' => 'Minor optimizations',
		'widgets/list-friend-like/index.tpl' => 'Minor optimizations',
		'widgets/list-like-button/Controller.php' => 'Minor optimizations',
		'widgets/page-friend-like/Controller.php' => 'Minor optimizations',
		'widgets/page-friend-like/index.tpl' => 'Minor optimizations',
		'widgets/page-like/Controller.php' => 'Minor optimizations',
		'widgets/page-like/index.tpl' => 'Minor optimizations',
		'widgets/pageevent-friend-like/Controller.php' => 'Minor optimizations',
		'widgets/pageevent-friend-like/index.tpl' => 'Minor optimizations',
		'widgets/pageevent-like/Controller.php' => 'Minor optimizations',
		'widgets/pageevent-like/index.tpl' => 'Minor optimizations',
		'widgets/recipe-friend-like/Controller.php' => 'Minor optimizations',
		'widgets/recipe-friend-like/index.tpl' => 'Minor optimizations',
		'widgets/recipe-like/Controller.php' => 'Minor optimizations',
		'widgets/recipe-like/index.tpl' => 'Minor optimizations',
		'widgets/list-like-forum/Controller.php' => 'Minor optimizations',
		'widgets/list-like-events/Controller.php' => 'Minor optimizations',
		'widgets/list-like-groups/Controller.php' => 'Minor optimizations',
		'widgets/list-like-listings/Controller.php' => 'Minor optimizations',
		'widgets/list-like-pages/Controller.php' => 'Minor optimizations',
		'widgets/list-like-polls/Controller.php' => 'Minor optimizations',
		'widgets/list-like-videos/Controller.php' => 'Minor optimizations',
		'widgets/list-like-album/Controller.php' => 'Minor optimizations',
		'widgets/list-like-blogs/Controller.php' => 'Minor optimizations',
		'widgets/list-like-classifieds/Controller.php' => 'Minor optimizations',
		'widgets/list-like-musics/Controller.php' => 'Minor optimizations',
		'views/scripts/settings_css.tpl' => 'Added',
  ),

  '4.1.7' => array(
    'settings/chnagelog.php' => 'Added',
		'widgets/list-browse-mixlikes/index.tpl' => 'Language Change',
		'Form/Admin/Global.php' => 'Language Change',
		'Form/Admin/Mix.php' => 'Language Change',
		'Form/Admin/Widget.php' => 'Language Change',
		'externals/styles/likesettings.css' => 'Minor optimizations',
		'externals/styles/main.css' => 'Added Activity Feed Liked Icon CSS',
		'views/scripts/_my-friends-likes.tpl' => 'Change collection_id into album_id',
		'views/scripts/index/profileuserlikes.tpl' => 'Change collection_id into album_id',
		'widgets/mix-like/index.tpl' => 'Change collection_id into album_id',
		'widgets/profile-user-likes/index.tpl' => 'Change collection_id into album_id',
  ),
)
?>
