<?php

/**
 * SocialEngine
 *
 * @category   Application_Extensions
 * @package    Sitegroupalbum
 * @copyright  Copyright 2010-2011 BigStep Technologies Pvt. Ltd.
 * @license    http://www.socialengineaddons.com/license/
 * @version    $Id: Controller.php 2011-08-026 9:40:21Z SocialEngineAddOns $
 * @author     SocialEngineAddOns
 */
class Sitegroupalbum_Widget_ListPhotosTabsViewController extends Engine_Content_Widget_Abstract {

  public function indexAction() {
    $this->view->is_ajax = $is_ajax = $this->_getParam('isajax', '');
    $this->view->showViewMore = $this->_getParam('showViewMore', 1);
    $this->view->category_id = $category_id = $this->_getParam('category_id',0);
    if (empty($is_ajax)) {
      $this->view->tabs = $tabs = Engine_Api::_()->getItemTable('seaocore_tab')->getTabs(array('module' => 'sitegroupalbum', 'type' => 'photos', 'enabled' => 1));
      $count_tabs = count($tabs);
      if (empty($count_tabs)) {
        return $this->setNoRender();
      }
      $activeTabName = $tabs[0]['name'];
    }

    $this->view->marginPhoto = $this->_getParam('margin_photo', 12);
    $this->view->showLightBox = Engine_Api::_()->sitegroup()->canShowPhotoLightBox();
    $tableGroup = Engine_Api::_()->getDbtable('groups', 'sitegroup'); 
    $tableGroupName = $tableGroup->info('name');
    $parentTable = Engine_Api::_()->getItemTable('sitegroup_album');
    $parentTableName = $parentTable->info('name');
    $table = Engine_Api::_()->getItemTable('sitegroup_photo');
    $tableName = $table->info('name');
    $select = $table->select()
										->setIntegrityCheck(false)
                    ->from($tableName)
                    ->joinLeft($tableGroupName, "$tableGroupName.group_id = $tableName.group_id", array('title AS group_title', 'photo_id as group_photo_id'));
    $select = $select
              ->where($tableGroupName . '.closed = ?', '0')
              ->where($tableGroupName . '.approved = ?', '1')
              ->where($tableGroupName . '.declined = ?', '0')
              ->where($tableGroupName . '.draft = ?', '1');

    if(!empty($category_id)) {
      $select->where($tableGroupName . '.	category_id =?', $category_id);
    }
    
    if (Engine_Api::_()->sitegroup()->hasPackageEnable()) {
      $select->where($tableGroupName . '.expiration_date  > ?', date("Y-m-d H:i:s"));
    }
    if (!Engine_Api::_()->sitegroup()->isLessThan417AlbumModule()) {
      $select->joinLeft($parentTableName, $parentTableName . '.album_id=' . $tableName . '.album_id', null);
    } else {
      $select->joinLeft($parentTableName, $parentTableName . '.album_id=' . $tableName . '.collection_id', null);
    }
    $select->where($parentTableName . '.search = ?', true);
    
    if(!Engine_Api::_()->getApi('settings', 'core')->getSetting('sitegroupalbum.hide.autogenerated', 1) ) {
			$select->where($parentTableName. '.default_value'.'= ?', 0);
			$select->where($parentTableName . ".type is Null");
    }     
    
    $paramTabName = $this->_getParam('tabName', '');
    if (!empty($paramTabName))
      $activeTabName = $paramTabName;

    $activeTab = Engine_Api::_()->getItemTable('seaocore_tab')->getTabs(array('module' => 'sitegroupalbum', 'type' => 'photos', 'enabled' => 1, 'name' => $activeTabName));

    $this->view->activTab = $activTab = $activeTab['0'];
    $type = null;
    switch ($activTab->name) {
      case 'recent_groupphotos':
        $type = 'creation_date';
        break;
      case 'liked_groupphotos':
        $type = 'like_count';
        $select->order($tableName . '.like_count DESC');
        break;
      case 'viewed_groupphotos':
        $type = 'view_count';
        $select->order($tableName . '.view_count DESC');
        break;
      case 'commented_groupphotos':
        $type = 'comment_count';
        $select->order($tableName . '.comment_count DESC');
        break;
      case 'featured_groupphotos':
        $type = 'featured';
        $select->where($tableName . '.featured = ?', 1);
        $select->order('Rand()');
        break;
      case 'random_groupphotos':
        $select->order('Rand()');
        break;
    }
    if ($activTab->name != 'featured_groupphotos' && $activTab->name != 'random_groupphotos') {
      $select->order($tableName . '.photo_id DESC');
    }

    $this->view->paginator = $paginator = Zend_Paginator::factory($select);
//     if (($paginator->getTotalItemCount() <= 0)) {
//       return $this->setNoRender();
//     }
    $paginator->setItemCountPerPage($activTab->limit);
    $paginator->setCurrentPageNumber($this->_getParam('group', 1));
    $this->view->count = $paginator->getTotalItemCount();
    $this->view->params = $params = array();
    if ($this->view->showLightBox && !empty($type)) {
      $this->view->params = $params = array('type' => $type, 'count' => $paginator->getTotalItemCount(), 'title' => $activTab->getTitle() . " Photos");
    }
    $this->view->canCreate = Engine_Api::_()->authorization()->isAllowed('sitegroupalbum', null, 'create');
  }

}

?>