<?php

/**
 * SocialEngine
 *
 * @category   Application_Extensions
 * @package    Sitestorealbum
 * @copyright  Copyright 2012-2013 BigStep Technologies Pvt. Ltd.
 * @license    http://www.socialengineaddons.com/license/
 * @version    $Id: Core.php 2013-09-02 00:00:00Z SocialEngineAddOns $
 * @author     SocialEngineAddOns
 */
class Sitestorealbum_Api_Core extends Core_Api_Abstract {

  /**
   * Delete the sitestore album and photos
   * 
   * @param int $album_id
   */
  public function deleteContent($album_id) {

		$album = Engine_Api::_()->getItem('sitestore_album', $album_id);

		if(empty($album)) {
			return;
		}

    //DELETE IMAGE
    $tablePhoto = Engine_Api::_()->getItemTable('sitestore_photo');
    $select = $tablePhoto->select()->where('album_id = ?', $album_id);
    $rows = $tablePhoto->fetchAll($select);
    if (!empty($rows)) {
      foreach ($rows as $photo) {
        $photo->delete();
      }
    }

    //DELETE ALBUM
    $album->delete();
  }
  
  /**
   * Truncation of text
   * @params string $text
   * @params int $limit
   * @return truncate text
   */
  public function truncateText($text, $limit) {
    $tmpBody = strip_tags($text);
    return ( Engine_String::strlen($tmpBody) > $limit ? Engine_String::substr($tmpBody, 0, $limit) . '..' : $tmpBody );
  }

  /**
   * get the featured photos
   */
  public function getFeaturedPhotos($params=array()) {
    $parentTable = Engine_Api::_()->getItemTable('sitestore_album');
    $parentTableName = $parentTable->info('name');
    $table = Engine_Api::_()->getItemTable('sitestore_photo');
    $tableName = $table->info('name');
    $select = $table->select()
                    ->from($tableName);
    if (!Engine_Api::_()->sitestore()->isLessThan417AlbumModule()) {
      $select
              ->joinLeft($parentTableName, $parentTableName . '.album_id=' . $tableName . '.album_id', null);
    } else {
      $select
              ->joinLeft($parentTableName, $parentTableName . '.album_id=' . $tableName . '.collection_id', null);
    }
    if (isset($params['category_id']) && !empty($params['category_id'])) {
        $tableStore = Engine_Api::_()->getDbtable('stores', 'sitestore');
				$tableStoreName = $tableStore->info('name');
        $select->join($tableStoreName, "$tableStoreName.store_id = $tableName.store_id", array())
				->where($tableStoreName . '.	category_id =?', $params['category_id']);
		}
    $select->where($parentTableName .'.search = ?', true)
            ->where($tableName . '.featured = ?', 1)
            ->order($tableName . '.creation_date DESC');

    if (isset($params['limit']) && !empty($params['limit'])) {
      if (!isset($params['start_index']))
        $params['start_index'] = 0;
      $select->limit($params['limit'], $params['start_index']);
    }
    
    if(!Engine_Api::_()->getApi('settings', 'core')->getSetting('sitestorealbum.hide.autogenerated', 1) ) {
			$select->where($parentTableName. '.default_value'.'= ?', 0);
			$select->where($parentTableName . ".type is Null");
    }     
    
    return $table->fetchAll($select);
  }

  /**
   * Return a truncate text
   *
   * @param text text 
   * @return truncate text
   * */
  public function truncation($string) {
    $length = Engine_Api::_()->getApi('settings', 'core')->getSetting('sitestorealbum.truncation.limit', 13);
    $string = strip_tags($string);
    return Engine_String::strlen($string) > $length ? Engine_String::substr($string, 0, ($length - 3)) . '...' : $string;
  }
  
  public function enableComposer() {
    $subject = '';
    if (Engine_Api::_()->core()->hasSubject()) {
      $subject = Engine_Api::_()->core()->getSubject();
    }
    if ($subject && in_array($subject->getType(), array('sitestore_store', 'sitestoreevent_event'))):
 

      if (in_array($subject->getType(), array('sitestoreevent_event'))):
        $subject = Engine_Api::_()->getItem('sitestore_store', $subject->store_id);
      endif;
      //PACKAGE BASE PRIYACY START
      if (Engine_Api::_()->sitestore()->hasPackageEnable()) {
        if (!Engine_Api::_()->sitestore()->allowPackageContent($subject->package_id, "modules", "sitestorealbum")) {
          return false;
        }
      } else {
        $isStoreOwnerAllow = Engine_Api::_()->sitestore()->isStoreOwnerAllow($subject, 'spcreate');
        if (empty($isStoreOwnerAllow)) {
          return false;
        }
      }
      if (!Engine_Api::_()->sitestore()->isManageAdmin($subject, 'edit') && !Engine_Api::_()->sitestore()->isManageAdmin($subject, 'spcreate')):
        return false;
      endif;

      return true;

    endif;
    return false;
  }
}

?>