<?php
/**
 * SocialEngine
 *
 * @category   Application_Extensions
 * @package    Blog
 * @copyright  Copyright 2006-2010 Webligo Developments
 * @license    http://www.socialengine.net/license/
 * @version    $Id: changelog.php 9140 2011-08-03 23:47:47Z john $
 * @author     John
 */
return array(
  '4.1.8' => array(
		'externals/styles/style_list.css' => 'Added styles ',
		'externals/styles/list_sponsored_featured.css' => 'Minor CSS Optimization',
		'Model/Photos.php' => 'Minor optimizations',
		'Plugin/Core.php' => 'Added static base URL for CDN support ',
		'settings/manifest.php' => 'Incremented version',
		'settings/my.sql' => 'Incremented version',
		'views/scripts/_FancyUpload.tpl' => 'Added static base URL for CDN support',
		'views/scripts/_FancyUploadVideo.tpl' => 'Added static base URL for CDN support',
		'views/scripts/_formEditImage.tpl' => 'Added static base URL for CDN support',
		'views/scripts/_formImagerainbowSponsred.tpl' => 'Added static base URL for CDN support',
		'views/scripts/_recently_popular_random_list.tpl' => 'Minor Optimizations ',
		'views/scripts/admin-items/add-category.tpl' => 'Added static base URL for CDN support',
		'views/scripts/index/create.tpl' => 'Added static base URL for CDN support',
		'views/scripts/index/edit.tpl' => 'Added static base URL for CDN support',
		'views/scripts/index/editaddress.tpl' => 'Added static base URL for CDN support',
		'views/scripts/index/editlocation.tpl' => 'Added static base URL for CDN support',
		'views/scripts/index/print.tpl' => 'Added static base URL for CDN support',
		'views/scripts/index/tellafriend.tpl' => 'Added static base URL for CDN support',
		'views/scripts/photo/view.tpl' => 'Added static base URL for CDN support',
		'views/scripts/review/create.tpl' => 'Added static base URL for CDN support',
		'views/scripts/review/edit.tpl' => 'Added static base URL for CDN support',
		'widgets/listing-like-button/index.tpl' => 'Minor Optimizations ',
		'widgets/listings-list/index.tpl' => 'Added static base URL for CDN support',
		'widgets/location-list/index.tpl' => 'Added static base URL for CDN support',
		'widgets/recently-popular-random-list/index.tpl' => 'Added static base URL for CDN support',
		'widgets/sponsored-list/index.tpl' => 'Added static base URL for CDN support',
		'widgets/suggestedlist-list/index.tpl' => 'Added static base URL for CDN support',
	),

  '4.1.7p1' => array(
		'Api/Core.php' => 'Minor modification for Suggestions / Recommendations Plugin',
		'controllers/AdminSettingsController.php' => 'Minor modification for Suggestions / Recommendations Plugin',
		'controllers/IndexController.php' => 'Minor CSS Optimization',
		'controllers/ReviewController.php' => 'Minor Optimizations',
		'controllers/VideoController.php' => 'Minor Optimizations',
		'controllers/VideoeditController.php' => 'Minor Optimizations',
		'externals/styles/list_sponsored_featured.css' => 'Minor CSS Optimization',
		'externals/styles/main.css' => 'Minor CSS Optimization',
		'externals/styles/style_print.css' => 'Added New Css File',
		'externals/styles/style_list.css' => 'Minor CSS Optimization',
		'externals/styles/admin/main.css' => 'Minor CSS Optimization',
		'Plugin/Core.php' => 'SEO optimization',
		'Plugin/Menus.php' => 'Minor CSS Optimization',
		'settings/install.php' => 'Minor modification for Suggestions / Recommendations Plugin',
		'settings/manifest.php' => 'Minor Optimizations',
		'settings/my.sql' => 'Incremented version',
		'settings/my-upgrade-4.1.7-4.1.7p1.sql' => 'Added',
		'views/scripts/admin-items/add-category.tpl' => 'Minor CSS Optimization',
		'views/scripts/admin-level/index.tpl' => 'Minor CSS Optimization',
		'views/scripts/admin-settings/faq.tpl' => 'Minor CSS Optimization',
		'views/scripts/admin-settings/index.tpl' => 'Minor Optimization',
		'views/scripts/admin-settings/readme.tpl' => 'Minor CSS Optimization',
		'views/scripts/admin-widgets/index.tpl' => 'Minor CSS Optimization',
		'views/scripts/index/likelist.tpl' => 'Minor CSS Optimization',
		'views/scripts/index/print.tpl' => 'Minor CSS Optimization',
		'views/scripts/photo/view.tpl' => 'Minor Optimizations',
		'views/scripts/video/index.tpl' => 'Minor Optimizations',
		'views/scripts/videoedit/edit.tpl' => 'Minor Optimizations',
		'widgets/information-list/index.tpl' => 'Fixed Issue of owner Photo',
		'widgets/listing-like/index.tpl' => 'Minor CSS Optimization',
		'widgets/popularlocation-list/index.tpl' => 'Minor CSS Optimization',
		'widgets/profile-list/index.tpl' => 'Minor CSS Optimization',
		'widgets/slideshow-list/index.tpl' => 'Minor CSS Optimization',
		'widgets/suggestedlist-list/Controller.php' => 'Fixed Log Error',
		'widgets/recently-popular-random-list/index.tpl' => 'Minor CSS Optimization',
		'widgets/review-list/Controller.php' => 'Minor Optimizations',
		'widgets/review-list/index.tpl' => 'Minor Optimizations',
		'widgets/video-list/index.tpl' => 'Minor Optimizations',
  ),

  '4.1.7' => array(
		'controllers/IndexController.php' => 'Fixed Draft problem, Minor optimizations',
		'widgets/video-list/Controller.php' => 'Fixed video bug',
		'settings/changelog.php' => 'Added',
		'settings/content.php' => 'Minor optimizations',
		'widgets/information-list/Controller.php' => 'Minor optimizations',
		'widgets/information-list/index.tpl' => 'Minor optimizations',
		'Plugin/Core.php' => 'Minor optimizations',
		'views/scripts/topic/index.tpl' => 'Minor optimizations',
		'controllers/AdminController.php' => 'Minor optimizations',
		'controllers/VideosearchController.php' => 'Minor optimizations',
		'controllers/AdminItemsController.php' => 'Minor optimizations',
		'settings/my-upgrade-4.1.6-4.1.7.sql' => 'Added',
		'settings/manifest.php' => 'Incremented version',
		'settings/my.sql' => 'Incremented version',
  ),
);